module.exports = {
  Motivation: [
    "Every small step counts — keep going.",
    "You're doing better than you think.",
    "Progress, not perfection.",
    "Today is a good day to try again.",
    "Discipline beats motivation — show up anyway.",
    "Believe in yourself, even on the days when it's difficult.",
    "Keep moving forward, one step at a time.",
    "Your effort today will become your strength tomorrow.",
    "Don't stop — you're closer than you think.",
    "Small progress is still progress.",
    "You don't have to be perfect to make progress.",
    "Keep going. Your future self will thank you.",
    "Difficult roads often lead to meaningful destinations.",
    "Trust the process and keep showing up.",
    "You've overcome difficult days before. You can do it again.",
    "Focus on what you can do today.",
    "One step today is better than standing still.",
    "Your consistency will take you places motivation cannot.",
    "Don't compare your chapter to someone else's story.",
    "Give yourself another chance today.",
    "You are capable of more than you realize.",
    "Keep your goals bigger than your excuses.",
    "Success starts with simply refusing to give up.",
    "Make today count.",
    "Your journey doesn't need to be fast. It just needs to continue.",
    "Be proud of how far you've come.",
    "A bad day doesn't mean a bad life.",
    "Keep working quietly. Let your results speak.",
    "You can start again at any moment.",
    "Stay patient. Good things take time.",
    "Your hard work will add up.",
    "Keep believing, keep learning, keep growing.",
    "Don't wait for the perfect moment — start with what you have.",
    "You are one decision away from a better direction.",
  ],
  Career: [
    "Your hard work is noticed, even when it doesn't feel like it.",
    "One good decision today compounds for years.",
    "Keep learning — it's your biggest edge.",
    "Consistency at work beats occasional brilliance.",
    "Every new skill opens another door.",
    "Your career grows when you keep growing.",
    "Don't be afraid to start as a beginner.",
    "The skills you build today can shape your tomorrow.",
    "Keep improving, even if the progress feels slow.",
    "Ask questions. Learn from mistakes. Keep moving forward.",
    "Your current position is not the limit of your potential.",
    "Stay curious — curiosity is a career advantage.",
    "Experience comes from doing, learning, and trying again.",
    "Build skills that make you valuable wherever you go.",
    "Your effort today can create opportunities tomorrow.",
    "Keep learning something new every day.",
    "Don't focus only on the destination — build yourself along the way.",
    "Good careers are built one skill at a time.",
    "Be patient with your professional growth.",
    "Your mistakes can become some of your best lessons.",
    "Keep showing up and improving your craft.",
    "A strong career is built through consistency, not shortcuts.",
    "Learn from people who are better than you.",
    "Take feedback as an opportunity to improve.",
    "Your work today is an investment in your future.",
    "Stay focused on becoming better, not just looking successful.",
    "Keep building your knowledge and experience.",
    "Opportunities often come to people who are prepared.",
    "Don't be afraid to take on something challenging.",
    "Your next opportunity may begin with the skill you're learning today.",
    "Professional growth takes time — keep going.",
    "Keep your goals clear and your learning continuous.",
    "Every project is an opportunity to learn something new.",
    "Your consistency can become your competitive advantage.",
    "Keep improving your skills and let your work speak for you.",
  ],
Romantic: [

  "Thinking of you right now. 💜",
  "You make ordinary days feel special.",
  "Just a reminder that you're loved.",
  "Can't stop smiling thinking about you.",
  "You make my world a little brighter.",
  "Every moment with you feels special.",
  "You're one of my favorite thoughts.",
  "I hope you know how much you mean to me. ❤️",
  "Just wanted to remind you that you're special to me.",
  "You have a way of making everything feel better.",
  "My day feels better whenever I hear from you.",
  "You're always somewhere in my thoughts.",
  "Life feels a little sweeter with you in it.",
  "I feel lucky to have you in my life.",
  "You make even simple moments memorable.",
  "Sending you a little love today. ❤️",
  "I hope something makes you smile today — preferably me.",
  "You are the kind of person who makes the heart feel at home.",
  "No special reason — just thinking about you.",
  "You make my ordinary days feel extraordinary.",
  "I could never get tired of talking to you.",
  "You have a special place in my heart.",
  "Just wanted to say that I appreciate you more than you know.",
  "Some people make life better just by being there. You're one of them.",
  "You make my heart smile.",
  "If I could send you a hug right now, I would.",
  "You're one of the best parts of my day.",
  "Just thinking about you made me smile.",
  "I hope your day is as wonderful as you are.",
  "You bring a little more happiness into my life every day.",
  "Sometimes I don't need a reason to miss you.",
  "You're always worth another thought, another smile, another message.",
  "Having you in my life means more than words can say.",
  "You make my heart feel lighter.",
  "I just wanted you to know that you're special.",

  // ❤️ More Romantic
  "If I had to choose my favorite place, I'd choose wherever you are.",
  "You somehow make my heart feel calm and excited at the same time.",
  "I don't need a perfect day, I just need a little time with you.",
  "Every time I talk to you, I fall for you a little more.",
  "You are my favorite notification. ❤️",
  "My favorite moments are the ones that have you in them.",
  "I wish I could pause time whenever I'm with you.",
  "You make my heart do things I can't explain.",
  "I never knew someone could become such a beautiful part of my life.",
  "You're not just someone I love, you're someone I feel lucky to know.",
  "Even on my busiest days, somehow you find your way into my thoughts.",
  "I don't know what tomorrow looks like, but I hope you're in it.",
  "You make me believe that the little things really matter.",
  "Being with you feels like finding something I didn't know I was missing.",
  "You make my heart feel like it has found its favorite place.",
  "I could listen to you talk for hours and still want more.",
  "You have no idea how often you make me smile without even trying.",
  "If love had a favorite person, mine would be you.",
  "You're the thought I don't mind getting distracted by.",
  "I wish every day had a little more of you in it.",

  // 💕 Hindi / Hinglish Romantic
  "Tumse baat hoti hai toh din apne aap better lagne lagta hai. ❤️",
  "Tum meri life ka woh part ho jise main kabhi lose nahi karna chahta.",
  "Bas tumhara naam screen par aata hai aur smile automatically aa jaati hai.",
  "Tum ho toh normal sa din bhi special lagta hai.",
  "Pata nahi tum mein kya hai, par dil baar-baar tumhari taraf hi chala jaata hai.",
  "Tumse baat karna meri daily routine ka favorite part hai.",
  "Tum meri favorite notification ho. ❤️",
  "Kabhi-kabhi bina kisi reason ke bhi tumhari yaad aa jaati hai.",
  "Tumhare saath chhoti si conversation bhi mere liye special hoti hai.",
  "Tum meri life mein ho, bas itna hi kaafi hai smile karne ke liye.",
  "Tumhari ek smile mera pura mood change kar sakti hai.",
  "Tumhare bina din thoda incomplete sa lagta hai.",
  "Dil ko sukoon bhi tumse hi milta hai aur smile bhi.",
  "Tumhare saath waqt ka pata hi nahi chalta.",
  "Mujhe tumhari aadat si ho gayi hai. ❤️",
  "Tumse baat na ho toh kuch missing sa lagta hai.",
  "Tum meri favorite person ho, simple.",
  "Tumhari presence hi mere liye kaafi special hai.",
  "Tumhare saath ordinary moments bhi memories ban jaate hain.",
  "Bas ek baar tum smile kar do, mera din ban jaata hai.",

  // 🥰 Cute Romantic
  "Can I officially make you my favorite person forever?",
  "You + Me + unlimited conversations = perfect plan.",
  "I think my heart has a little crush on you. ❤️",
  "You're dangerously easy to fall for.",
  "I blame you for all these random smiles.",
  "You're the reason my phone gets checked way too often.",
  "I don't need coffee when your message can wake me up.",
  "You make being cheesy feel completely worth it.",
  "I think my heart has memorized your name.",
  "You're my favorite kind of distraction.",
  "If missing you was a job, I'd be working overtime.",
  "I wish I could teleport to you for just one hug.",
  "You make me want to be a little more romantic every day.",
  "You're cute, but unfortunately for me, you're also impossible to ignore.",
  "I think you secretly have a permanent reservation in my heart.",

  // 😘 Light Teasing + Romantic
  "Stop being so cute, I'm trying to concentrate here.",
  "How am I supposed to focus when you're constantly on my mind?",
  "You know you're becoming my favorite habit, right?",
  "Honestly, it's getting difficult to pretend I don't miss you.",
  "You owe me a smile for making me think about you this much.",
  "Why do you have to be this adorable? It's unfair.",
  "I was going to be productive today, then I thought about you.",
  "You're becoming a serious distraction and I'm not complaining.",
  "I think you owe my heart an explanation.",
  "You really need to stop being this lovable.",
  "I hope you realize how much trouble you cause by being this cute.",
  "You're lucky you're adorable, otherwise I'd complain about how much I miss you.",

  // 💘 Romantic Pickup Lines
  "Are you my favorite song? Because I could listen to you all day.",
  "Are you a magician? Because whenever I see you, everything else disappears.",
  "Do you have a map? Because I keep getting lost in your eyes.",
  "Are you made of magic? Because you make my bad days disappear.",
  "If smiles were currency, you'd make me the richest person alive.",
  "Are you my notification? Because I get excited every time you appear.",
  "If I could rearrange the alphabet, I'd put U and I together.",
  "Are you the reason my heart beats faster, or should I blame the coffee?",
  "If loving you was a full-time job, I'd happily work overtime.",
  "Do you believe in love at first message? Because yours definitely got my attention.",
  "Tum Wi-Fi ho kya? Kyunki tumhare bina connection incomplete lagta hai. 😜",
  "Tum Google ho kya? Kyunki jo mujhe chahiye tha, woh tum mein mil gaya.",
  "Tum charger ho kya? Kyunki tumhare bina meri battery low lagti hai.",
  "Tum coffee ho kya? Kyunki tumhare bina morning incomplete lagti hai.",
  "Tum itni cute kyun ho? Kya mere heart ko test karna hai? ❤️",
  "Tumhe dekh ke lagta hai Cupid ne mera address sahi pakda tha.",
  "Agar tum ek notification hoti, toh main tumhe kabhi swipe nahi karta.",
  "Tum meri favorite distraction ho, aur main distract hone ke liye ready hoon.",
  "Tumhare smile ka koi subscription hai kya? Main lifetime wala lena chahta hoon.",
  "Tum paas hoti ho toh dil ko lagta hai ki sab kuch perfect hai.",

],
Flirt: [
  // Romantic
  "You have this beautiful way of making my worst days feel better. ❤️",
  "Tumhari ek smile mera poora mood change kar deti hai.",
  "I don't need a perfect day, I just need a little time with you.",
  "Tumse baat na ho toh din thoda incomplete sa lagta hai.",
  "You are easily my favorite person to think about.",
  "Tum meri life ka woh part ho jise main kabhi boring nahi hone dunga. ❤️",

  // Compliments
  "You look absolutely gorgeous today.",
  "Tum bina try kiye bhi itni cute kaise lagti ho?",
  "Your smile is honestly my biggest weakness. ❤️",
  "Tumhari aankhon mein kuch toh magic hai.",
  "You have the kind of beauty that gets better every time I see you.",
  "Tumhari simplicity hi tumhe sabse zyada beautiful banati hai.",
  "I swear, you get prettier every time I see you.",
  "Tumhari smile dekhkar automatically smile aa jaati hai.",

  // Pick-up Lines - English
  "Are you a magician? Because whenever I see you, everyone else disappears. 😉",
  "Do you have a map? Because I keep getting lost in your eyes.",
  "Are you Wi-Fi? Because I'm really feeling a connection. 😏",
  "If being beautiful was a crime, you'd definitely be guilty.",
  "Are you my favorite notification? Because I always get excited when you pop up.",
  "Do you believe in love at first sight, or should I walk past you again? 😏",
  "I must be a photographer, because I can totally picture us together.",
  "Are you made of caffeine? Because you keep me awake thinking about you.",
  "If smiles were currency, you'd make me rich.",
  "Is your name Google? Because you have everything I've been searching for. ❤️",
  "I was going to use a clever pickup line, but then I saw you and forgot what I wanted to say.",
  "Are you a time traveler? Because I can see you in my future. ❤️",

  // Pick-up Lines - Hindi / Hinglish
  "Tum Google ho kya? Kyunki jo mujhe chahiye tha, woh tum mein mil gaya. 😏",
  "Tum Wi-Fi ho kya? Kyunki tumhare paas aate hi connection strong ho jaata hai. 😂❤️",
  "Tum chai ho kya? Kyunki tumhare bina mera din start hi nahi hota.",
  "Tumhari smile ka password kya hai? Main roz unlock karna chahta hoon. 😏",
  "Tum moonlight ho kya? Kyunki tum aate hi sab kuch beautiful lagne lagta hai.",
  "Tum itni cute ho ya meri aankhon ko tumse pyaar ho gaya hai?",
  "Tum calculator ho kya? Kyunki tumhare saath mera heart rate calculate hi nahi ho raha. 😂",
  "Agar tum ek song hoti, toh main tumhe repeat pe sunta rehta.",
  "Tumhare paas extra heart hai kya? Mera toh tum le gayi. ❤️",
  "Tum coffee ho kya? Kyunki tumhare bina mood nahi banta.",
  "Tum meri favourite notification kyun ho? Kyunki tumhara naam screen par aate hi smile aa jaati hai.",
  "Tumhe dekhne ke baad mujhe lagta hai ki meri choice actually kaafi achhi hai. 😏",

  // Cute
  "I think you have officially become my favorite distraction.",
  "Tumhari yaad aati hai toh bina reason ke phone check karne lagta hoon.",
  "You make me smile without even trying.",
  "Aaj bas tumhari thodi extra attention chahiye. 🥺❤️",
  "Tumhare messages meri daily dose of happiness hain.",
  "I could talk to you for hours and still want more.",
  "Tum jab mujhe tease karti ho na, mujhe secretly bahut achha lagta hai.",
  "You are cute enough to get away with almost anything. 😏",
  "Tum meri favourite problem ho jiska solution main kabhi nahi chahta.",
  "I think I'm getting dangerously addicted to talking to you.",

  // More romantic
  "I feel lucky every time I get to call you mine. ❤️",
  "Tumhare saath bitaya hua simple sa moment bhi special ban jaata hai.",
  "I love the way you make me feel completely comfortable being myself.",
  "Tum meri favourite person ho jisse main har chhoti-badi baat share karna chahta hoon.",
  "You make my heart feel at home.",
  "Tum paas hoti ho toh sab kuch automatically better lagta hai.",
  "I never get tired of hearing your voice.",
  "Tumhari care mere liye words se kahin zyada important hai.",
  "You are not just someone I love, you are someone I genuinely enjoy being around.",
  "Tumhari presence hi mere liye kaafi hai mera din better banane ke liye.",

  // Teasing
  "Why are you always this cute? I'm trying to concentrate here. 😏",
  "Tum jaan-bujhkar mujhe distract karti ho na? 😂",
  "I blame you for all these random smiles on my face.",
  "Tumhe pata hai na tum meri weakness ho, phir bhi itni cute banti rehti ho. 😏",
  "I was trying to behave today, but then you texted me.",
  "Tumhare saath flirt karna ab meri daily routine ban gayi hai.",
  "I think you secretly enjoy making me miss you.",
  "Aaj phir tumne mera focus kharab kar diya. 😂❤️",
  "Tum itni adorable kyun ho? Normal behave karna mushkil ho jaata hai.",
  "I was going to ignore you for five minutes, but I lasted approximately three seconds. 😂",

  // Pick-up + girlfriend vibe
  "If I had to choose my favorite place, I'd probably choose wherever you are. ❤️",
  "Tum agar mere saamne hoti toh abhi pickup line nahi, seedha hug milta. 🫂",
  "I don't need a pickup line anymore, I already got the girl I wanted. ❤️",
  "Tumhe impress karne ki zarurat nahi, tum already mera heart jeet chuki ho.",
  "If I could pause one moment, it would be one where I'm smiling with you.",
  "Tum meri favourite person ho, aur haan, favourite distraction bhi. 😏",
  "I may not have the perfect words, but I know exactly how much I adore you.",
  "Tumhe dekhkar har baar ek hi thought aata hai — yaar, kitni lucky life hai meri. ❤️",
  "If loving you is a habit, I don't want to quit.",
  "Tum meri life ki woh notification ho jise main kabhi mute nahi karna chahta.",

  // More Hindi
  "Mujhe tumhari aadat nahi lagi, mujhe tumhari mohabbat ho gayi hai. ❤️",
  "Tumhari ek 'miss you' meri saari complaints khatam kar sakti hai.",
  "Tumhari smile ke liye main roz ek naya reason dhoond sakta hoon.",
  "Mujhe tumhari woh chhoti-chhoti baatein bhi bahut pasand hain jo tum khud notice nahi karti.",
  "Tumse baat karte-karte time kab nikal jaata hai, pata hi nahi chalta.",
  "Kabhi-kabhi bas tumhe dekhta rahun aur kuch na bolun, itna hi kaafi hai.",
  "Tum meri favourite feeling ho.",
  "Aaj tumhari bahut yaad aa rahi hai, so obviously message toh banta hai. ❤️",
  "Tumhare saath har normal day bhi thoda special lagta hai.",
  "Bas tum khush raho aur smile karti raho, baaki main dekh lunga. ❤️",

  // More English
  "You are the kind of person I could never get tired of choosing.",
  "I love how one message from you can completely change my mood.",
  "You are my favorite reason to smile at my phone.",
  "I don't know how you do it, but you always manage to make me miss you.",
  "You make flirting feel effortless. 😏",
  "I could probably write a hundred pickup lines, but none would explain how much I like you.",
  "You are my favorite person to annoy, tease, love, and miss. ❤️",
  "Every time I see you, I somehow like you a little more.",
  "You have no idea how much happiness you bring into my life.",
  "I don't need an excuse to text you. Missing you is enough.",
  "If I had one wish right now, I'd probably use it to see you.",
  "You make my heart do things I can't explain.",
  "I love being the reason behind your smile.",
  "You are the sweetest distraction I never want to get rid of.",
  "I think my favorite view will always be you smiling at me. ❤️",

  // Final playful pickup lines
  "Are you my alarm? Because you are the first thing I want to wake up to. ❤️",
  "Tum password ho kya? Kyunki mere dil ka access sirf tumhare paas hai. 😏",
  "Are you a camera? Because every time I see you, I smile.",
  "Tum meri playlist ka favourite song ho, baar-baar tumhare paas hi aata hoon. ❤️",
  "Are you a sunset? Because I could stare at you forever.",
  "Tum chocolate ho kya? Kyunki tumhe dekhte hi mood sweet ho jaata hai. 😂❤️",
  "If beauty had a notification, my phone would probably be full because of you.",
  "Tum meri lucky charm ho kya? Kyunki tumse baat hote hi din better ho jaata hai.",
  "If I could turn every thought of you into a smile, I'd be smiling all day.",
  "Tumse milna coincidence tha, tumhe pasand karna choice thi, aur tumse pyaar hona bilkul natural ho gaya. ❤️",
],
  Compliment: [
    "You handle things with more grace than you realize.",
    "Your energy makes a difference to the people around you.",
    "You're sharper than you give yourself credit for.",
    "The way you show up for people is rare.",
    "You have a really positive presence.",
    "You make people feel comfortable being themselves.",
    "Your effort doesn't go unnoticed.",
    "You have a way of making difficult things look easier.",
    "You're more capable than you give yourself credit for.",
    "Your attitude can brighten someone's entire day.",
    "You bring something unique wherever you go.",
    "You're the kind of person people can count on.",
    "Your kindness says a lot about you.",
    "You have a wonderful way of handling challenges.",
    "You're doing more right than you probably realize.",
    "Your determination is genuinely impressive.",
    "You have a great ability to keep going when things get difficult.",
    "People are lucky to have someone like you around.",
    "You have a naturally positive energy.",
    "You're stronger than you think.",
    "Your sincerity makes you stand out.",
    "You have a good heart, and it shows.",
    "Your presence can make a room feel better.",
    "You deserve credit for how much effort you put in.",
    "You have a great balance of confidence and humility.",
    "The way you care about others is something special.",
    "You're someone worth appreciating.",
    "You make a bigger difference than you probably realize.",
    "Your growth is something to be proud of.",
    "You have a quality that makes people want to trust you.",
    "You're genuinely easy to appreciate.",
    "Your patience and effort are admirable.",
    "You bring value simply by being yourself.",
    "Your positive attitude is contagious.",
    "You deserve to hear good things about yourself too.",
  ],
  Shayari: [
    "Waqt badal jaata hai, par kuch pal hamesha yaad rehte hain.",
    "Mehnat itni khamosh ho, ke safalta shor macha de.",
    "Raaste mushkil the, par himmat kabhi kam nahi hui.",
    "Khwaab wahi hain, bas unhe poora karne ka junoon badh gaya hai.",
    "Hausla rakho, manzil ek din zaroor milegi.",
    "Kuch safar manzil se zyada khoobsurat hote hain.",
    "Jo waqt guzar gaya, woh sabak tha; jo aane wala hai, woh mauka hai.",
    "Umeed ki ek kiran bhi andhere ko hara sakti hai.",
    "Kadam chhote sahi, par safar jaari rehna chahiye.",
    "Zindagi har roz ek nayi kahani likhti hai.",
    "Muskurate raho, waqt khud badal jayega.",
    "Koshish karne walon ki kabhi haar nahi hoti.",
    "Sapne wahi khoobsurat hote hain jinke liye dil se mehnat ki jaaye.",
    "Khamoshi se ki gayi mehnat ek din sabko nazar aati hai.",
    "Himmat ho to mushkilein bhi raaste ban jaati hain.",
    "Har raat ke baad ek nayi subah zaroor hoti hai.",
    "Manzil door ho sakti hai, namumkin nahi.",
    "Waqt sabka aata hai, bas intezaar aur mehnat zaroori hai.",
    "Jo dil se chaha ho, uske liye hausla bhi dil se rakho.",
    "Zindagi mein sukoon bhi zaroori hai aur junoon bhi.",
    "Kuch yaadein waqt ke saath aur bhi khoobsurat ho jaati hain.",
    "Dil saaf ho to alfaaz kam bhi kaafi hote hain.",
    "Safar mushkil ho to kya, hausla kam nahi hona chahiye.",
    "Har pal ko jee lo, kal sirf ek khayal hai.",
    "Umeed ka diya kabhi bujhne mat dena.",
    "Jo mil gaya uska shukr, jo nahi mila uska sabr.",
    "Dil mein umeed ho to raaste khud nazar aane lagte hain.",
    "Kuch log zindagi mein aakar use aur khoobsurat bana dete hain.",
    "Mohabbat lafzon ki mohtaaj nahi hoti.",
    "Ek achhi yaad poore din ko khoobsurat bana sakti hai.",
    "Rishte waqt se nahi, ehsaas se mazboot hote hain.",
    "Zindagi chhoti si hai, ise muskurakar jeena chahiye.",
    "Khushiyon ko kal par mat chhodo, aaj bhi ek khoobsurat din hai.",
    "Dil se nikli baat aksar dil tak pahunchti hai.",
    "Har mod par ek nayi kahani tumhara intezaar kar rahi hai.",
  ],
  Festival: [
    "Wishing you a day full of good moments!",
    "Hope today brings something worth celebrating.",
    "Wishing you happiness, peace, and beautiful memories today.",
    "May your day be filled with smiles and positive moments.",
    "Sending warm wishes and good vibes your way!",
    "Hope this special day brings lots of happiness to you and your family.",
    "Wishing you a celebration filled with joy and laughter.",
    "May today bring new memories and countless reasons to smile.",
    "Have a beautiful and memorable celebration!",
    "Sending you heartfelt wishes on this special occasion.",
    "May your day be bright, peaceful, and full of happiness.",
    "Wishing you and your loved ones a wonderful celebration.",
    "Hope this occasion brings positivity and happiness into your life.",
    "Celebrate the little moments and enjoy the day!",
    "May this special occasion fill your heart with joy.",
    "Wishing you good health, happiness, and beautiful moments.",
    "Have a joyful celebration surrounded by people you love.",
    "May your home be filled with happiness and laughter.",
    "Sending you lots of positivity and warm wishes today.",
    "Hope this celebration becomes a beautiful memory.",
    "Wishing you a peaceful and joyful day.",
    "May every moment today bring a reason to smile.",
    "Have a wonderful celebration and an even better year ahead.",
    "Warm wishes to you and your family on this special day.",
    "May happiness follow you today and always.",
    "Enjoy the celebration and make some wonderful memories!",
    "Wishing you endless happiness on this beautiful occasion.",
    "May this day bring peace, prosperity, and positivity.",
    "Have a fantastic day filled with laughter and love.",
    "Best wishes for a happy and memorable celebration.",
    "May the spirit of this occasion bring everyone closer together.",
    "Wishing you many beautiful moments today and in the days ahead.",
    "Hope your celebration is as wonderful as you deserve.",
    "Sending happiness, smiles, and warm wishes your way!",
  ],
};
module.exports.ALL_CATEGORIES = Object.keys(module.exports);
